services:
    php:
        build: ./
        volumes:
            - ./:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        env_file: .env
        working_dir: /var/www
    nginx:
        image: nginx
        volumes:
            - ./:/var/www
            - ./sslcert:/etc/nginx/sslcert
#            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx-www.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php